# Name of the session
name: frontend

# Root directory of the session
root: ~/dev/learning/k8s/potato

clear_panes: true

windows:
  - editor:
      layout: main-vertical
      panes:
        - vim
        -

  - server:
    panes:
      - yarn start
