name: Deploy
on:
  push:
    # branches:
    #   - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: potato
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
